# Generated by Django 3.1.5 on 2024-07-09 23:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('research_procedures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_allocations',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 7, 9)),
        ),
        migrations.CreateModel(
            name='co_project_investigator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_pi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_procedures.projects')),
            ],
            options={
                'ordering': ['-co_pi_id'],
            },
        ),
        migrations.CreateModel(
            name='co_pis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_pi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_procedures.projects')),
            ],
            options={
                'ordering': ['-project_id'],
            },
        ),
    ]
