# Generated by Django 3.1.5 on 2025-01-13 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0006_clubposition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fest_budget',
        ),
    ]
