# Generated by Django 3.1.5 on 2025-01-27 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0006_clubposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('images', models.ImageField(null=True, upload_to='gymkhana/event_images')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymkhana.event_info')),
            ],
        ),
    ]
