# Generated by Django 3.1.5 on 2025-01-13 21:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0007_delete_fest_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Technical', 'Technical'), ('Sports', 'Sports'), ('Cultural', 'Cultural')], max_length=50)),
                ('description', models.TextField(max_length=256, null=True)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, max_length=50)),
                ('link', models.CharField(max_length=256, null=True)),
            ],
            options={
                'db_table': 'fest',
            },
        ),
    ]
