# Generated by Django 3.1.5 on 2025-01-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0008_fest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fest',
            name='date',
            field=models.DateTimeField(default=None),
        ),
    ]
