# Generated by Django 3.1.5 on 2025-03-21 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0008_auto_20250217_1709'),
        ('gymkhana', '0007_eventinput'),
    ]

    operations = [
    ]
