# Generated by Django 3.1.5 on 2025-01-19 22:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0009_auto_20250113_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fest',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, max_length=50),
        ),
    ]
