# Generated by Django 3.1.5 on 2025-01-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0010_auto_20250119_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fest',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
