# Generated by Django 3.1.5 on 2025-01-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0011_auto_20250120_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fest',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
